name: "unit-test"
on:
  push:

jobs:
  test:
    name: Run unit tests

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: akenetest
          POSTGRES_NAME: akenetest
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: akenetest
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Install psycopg2
        run: pip install psycopg2-binary

      - name: Run migrations
        run: pw_migrate  migrate --database $DATABASE_URL
        env:
          DATABASE_URL: postgres://akenetest:akenetest@localhost:5432/akenetest

      - name: Run unit tests
        run: |
          pytest --junitxml=test-report.xml
        env:
          DATABASE_URL: postgres://akenetest:akenetest@localhost:5432/akenetest
          CONFIG_MODULE: config.example

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-report.xml